FROM ghcr.io/coopnorge/engineering-docker-images/e0/devtools-golang-v1beta1:latest@sha256:fe2abe01ae79f1cb3a17173e61f4dce8d3c29358ffcbe27cc7d6571ee994d515 AS golang-devtools
# Do not remove, used by pallet validation
FROM ghcr.io/coopnorge/engineering-docker-images/e0/devtools-kubernetes-v1beta1:latest@sha256:35ebf35de97834a70990f03a6ba3a9dc7dccba308ae7cc81171306de2258ea05 AS kubernetes-devtools
